# Generated by Django 2.1.8 on 2019-04-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=500, null=True)),
                ('fee', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('organized_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/event')),
            ],
        ),
        migrations.CreateModel(
            name='EventReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('squadname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Squad Name')),
                ('membernumber', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], default=0, max_length=10, verbose_name='Player Number')),
                ('p1name', models.CharField(blank=True, max_length=255, null=True)),
                ('p1userid', models.CharField(blank=True, max_length=50, null=True)),
                ('p2name', models.CharField(blank=True, max_length=255, null=True)),
                ('p2userid', models.CharField(blank=True, max_length=50, null=True)),
                ('p3name', models.CharField(blank=True, max_length=255, null=True)),
                ('p3userid', models.CharField(blank=True, max_length=50, null=True)),
                ('p4name', models.CharField(blank=True, max_length=255, null=True)),
                ('p4userid', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventDetail')),
            ],
        ),
    ]
