# Generated by Django 2.1.8 on 2019-04-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190401_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreg',
            name='membernumber',
            field=models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four')], max_length=10),
        ),
        migrations.AlterField(
            model_name='eventreg',
            name='squadname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventreg',
            name='title',
            field=models.ForeignKey(on_delete='CASCADE', to='event.EventDetail'),
        ),
    ]
