# Generated by Django 2.1.8 on 2019-04-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190403_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreg',
            name='membernumber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='eventreg',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventDetail'),
        ),
    ]
